drop table if exists comments, bookings, items, requests, users cascade;

create table if not exists users (
    id bigint generated by default as identity primary key,
    name varchar(255),
    email varchar(512),
    constraint uq_user_email unique(email)
);

create table if not exists requests (
    id bigint generated by default as identity primary key,
    description varchar(512),
    created timestamp without time zone,
    requester_id bigint,
    constraint fk_requests_to_users foreign key(requester_id) references users(id) on delete cascade
);

create table if not exists items (
    id bigint generated by default as identity primary key,
    name varchar(255),
    description varchar(512),
    is_available boolean,
    owner_id bigint,
    request_id bigint,
    constraint fk_items_to_users foreign key(owner_id) references users(id) on delete cascade,
    constraint fk_items_to_requests foreign key(request_id) references requests(id) on delete cascade
);

create table if not exists bookings (
    id bigint generated by default as identity primary key,
    start_date timestamp without time zone,
    end_date timestamp without time zone,
    status varchar(20),
    item_id bigint,
    booker_id bigint,
    constraint fk_bookings_to_users foreign key(booker_id) references users(id) on delete cascade,
    constraint fk_bookings_to_items foreign key(item_id) references items(id) on delete cascade
);

create table if not exists comments (
    id bigint generated by default as identity primary key,
    text varchar(512),
    item_id bigint references items (id),
    author_id bigint references users (id),
    constraint fk_comments_to_users foreign key(author_id) references users(id) on delete cascade,
    constraint fk_comments_to_items foreign key(item_id) references items(id) on delete cascade
);